# Generated by Django 5.1.7 on 2025-03-18 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0003_remove_hotel_owner_hotel_username_alter_hotel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='username',
        ),
    ]
