# Generated by Django 5.1.7 on 2025-03-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0007_client_hotel_reservation_hotel_alter_room_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='hotel_profiles.hotel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='hotel_profiles.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel_profiles.hotel'),
        ),
        migrations.CreateModel(
            name='DailyReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_bookings', to='hotel_profiles.client')),
                ('hotel', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='daily_reservations', to='hotel_profiles.hotel')),
                ('profit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profit_records', to='hotel_profiles.client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_rooms', to='hotel_profiles.room')),
            ],
        ),
    ]
