# Generated by Django 5.1.7 on 2025-03-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0009_alter_dailyreservation_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
