# Generated by Django 5.1.7 on 2025-03-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0011_alter_client_hotel_alter_dailyreservation_hotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hotel',
        ),
    ]
