# Generated by Django 5.1.7 on 2025-03-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0012_rename_name_hotel_user_remove_client_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='client',
            new_name='client_id',
        ),
    ]
