# Generated by Django 5.1.7 on 2025-03-26 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0013_rename_client_reservation_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='client_id',
            new_name='client',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dailyreservation',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='hotel_profiles.room'),
        ),
    ]
