# Generated by Django 5.1.7 on 2025-03-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0014_rename_client_id_reservation_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_id',
        ),
    ]
