# Generated by Django 5.1.7 on 2025-04-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0016_client_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tg_id',
            field=models.DecimalField(decimal_places=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
