# Generated by Django 5.1.7 on 2025-04-18 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0017_hotel_tg_id_alter_hotel_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='tg_id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='TgId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
                ('tg_id', models.DecimalField(decimal_places=0, max_digits=9, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tgid', to='hotel_profiles.hotel')),
            ],
        ),
    ]
