# Generated by Django 5.1.7 on 2025-04-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0018_remove_hotel_tg_id_alter_room_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgid',
            name='position',
            field=models.CharField(blank=True, choices=[('staff', 'Staff'), ('boss', 'Boss')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='tgid',
            name='tg_id',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
    ]
