# Generated by Django 5.1.7 on 2025-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0019_alter_tgid_position_alter_tgid_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.CharField(choices=[('available', 'Availabe'), ('unavailable', 'Unavailable'), ('reserved', 'reserved')], default='available', max_length=15),
        ),
    ]
