# Generated by Django 5.1.7 on 2025-05-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0020_reservation_deposit_amount_alter_room_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='is_available',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('reserved', 'Reserved')], default='available', max_length=15),
        ),
    ]
