# Generated by Django 5.1.7 on 2025-05-25 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0021_alter_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel_profiles.hotel'),
        ),
    ]
