# Generated by Django 5.1.7 on 2025-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0022_client_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgid',
            name='tg_id',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='tgid',
            constraint=models.UniqueConstraint(condition=models.Q(('position', 'staff')), fields=('hotel',), name='unique_staff_per_hotel'),
        ),
        migrations.AddConstraint(
            model_name='tgid',
            constraint=models.UniqueConstraint(condition=models.Q(('position', 'boss')), fields=('hotel',), name='unique_boss_per_hotel'),
        ),
    ]
