# Generated by Django 5.1.7 on 2025-05-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0023_alter_tgid_tg_id_tgid_unique_staff_per_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='plan',
            field=models.TextField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='basic', max_length=10),
        ),
    ]
