# Generated by Django 5.1.7 on 2025-05-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0024_hotel_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='last_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
