# Generated by Django 5.1.7 on 2025-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_profiles', '0025_hotel_last_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('price', models.PositiveIntegerField(help_text="Narx so'mda (UZS)")),
                ('description', models.TextField(blank=True)),
                ('max_rooms', models.PositiveIntegerField()),
                ('telegram_notifications', models.BooleanField(default=True)),
                ('financial_reports', models.BooleanField(default=False)),
                ('export_excel', models.BooleanField(default=False)),
                ('multi_hotel', models.BooleanField(default=False)),
            ],
        ),
    ]
